version: '3.3'

services: 
    fooapp-nginx: 
        image: fooapp-frontend-nginx:1.0.0
        container_name: fooapp-nginx
        build: 
            context: .
            dockerfile: nginx.Dockerfile
        networks:
            - fooapp-net
        volumes:
            - ./nginx/conf/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
        ports:
            - '80:80'
            - '443:443'
        restart: always
    fooapp:
        image: fooapp-frontend:1.0.0
        container_name: fooapp-frontend
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - fooapp-net
        # volumes:
            # - ./.env:/usr/src/app/.env
        ports:
            - '3000:3000'
        restart: always 
networks:
    fooapp-net:
        driver: bridge